### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by danichispa**
Missing strings

### CODE REVIEW

**Comment by magnumdoomguy** [comment]
Thanks so much!  I really appreciate it!

**Comment by magnumdoomguy** [comment]
What's your user name on the Plex forums?  I'd like to include you in the development PM thread.

**Comment by AeronNL** [comment]
It is Arjan1105.
Did you send this email from Github?
I couldn’t find it on the Plex PM part :)

**Comment by AeronNL** [comment]
Wait, was this for me? Haha!

**Comment by danichispa** [comment]
If it's for me :wink: my username on plex forums is danichispa

**Comment by AeronNL** [comment]
It must be for you!:)

**Pull request merged**
